// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taxxlwkbfeecscisxqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheHhsd2tiZmVlY3NjaXN4cWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDY2MzMsImV4cCI6MjA2NTIyMjYzM30.9R1QUMuZ5gfp_ti4CJ4b2zBJp_bBwaiz2bZtpHxTaE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);